### ISSUE TITLE
add a health-check endpoint

### ISSUE THREAD

**Issue by 0xadada** [0xadada/vital-cause#1]
a health check endpoint should

* [ ] reside at `/health`
* [ ] accept `text/plain` content-type
* [ ] must be authenticated with the `?token=` query parameter, and that token must be equal to the value provided in the `AUTH_TOKEN` environment variable provided in the `.env` file.
* [ ] respond with `200 OK` HTTP code to a `GET` request
* [ ] respond with `403 Forbidden` if none of the above apply

**Comment by satblip** [comment]
Hi, here is my pull request, hope you like it :) https://github.com/0xadada/vital-cause/pull/2

**Comment by 0xadada** [comment]
fixed by https://github.com/0xadada/vital-cause/pull/2
