### ISSUE TITLE
implement a build pipeline

### ISSUE THREAD

**Issue by 0xadada** [0xadada/vital-cause#6]
## do

* [ ] add a CircleCI `.circleci/config.yml` file
* [ ] add auth hooks with CircleCI
* [ ] add build badge to readme
* [ ] tests should run on PRs and pushes

**Comment by hyperhtml** [comment]
I'd like to take this on as well.

**Comment by 0xadada** [comment]
fixed in https://github.com/0xadada/vital-cause/pull/13
